---
# tasks file for grafana

- include_role:
    name: docker

- name: "grafana : Pull docker image"
  community.docker.docker_image:
    name: "{{ grafana_image }}:{{ grafana_version }}"
    source: pull

# Image can't be tagged as 'latest' for nomad local docker images so we'll use
# 'local' instead
- name: "grafana : Tag image as local"
  community.docker.docker_image:
    name: "{{ grafana_image }}:{{ grafana_version }}"
    repository: "{{ grafana_image }}:local"
    force_tag: yes
    source: local
