---

- name: Reload systemd
  become: yes
  systemd:
    daemon_reload: yes

- name: Restart consul
  become: yes
  systemd:
    name: consul
    state: restarted

- name: Restart systemd-resolved
  become: yes
  systemd:
    name: systemd-resolved
    state: restarted