---
# defaults file for minio client

mc_name: mc
mc_checksum: sha256:01f866e9c5f9b87c2b09116fa5d7c06695b106242d829a8bb32990c00312e891
mc_version: RELEASE.2025-08-13T08-35-41Z
mc_version_success_string: "{{ mc_version }}"
mc_version_cmd: mc --version
mc_url: "https://dl.min.io/client/mc/release/linux-amd64/archive/mc.{{ mc_version }}"
mc_downloaded_file: "mc.{{ mc_version }}"
mc_extracted_path: "mc.{{ mc_version }}"
