---
cruisemic_name: cruisemic
cruisemic_checksum: sha256:d417a97ac7780de98815d2f11fca2212304d14212956bd0600df4f18c5e93904
cruisemic_version: v0.6.5
cruisemic_version_success_string: "{{ cruisemic_version }}"
cruisemic_version_cmd: "{{ cruisemic_name }} -version"
cruisemic_downloaded_file: "cruisemic.{{ cruisemic_version }}.linux-amd64"
cruisemic_url: "https://github.com/ctberthiaume/cruisemic/releases/download/{{ cruisemic_version }}/{{ cruisemic_downloaded_file }}"
cruisemic_extracted_path: "{{ cruisemic_downloaded_file }}"
