---
# defaults file for minio

minio_name: minio
minio_checksum: sha256:e3711a11e76a291aba1116ef1517ede335d31fb200c369e55a79b9be641b0b91
minio_version: RELEASE.2023-01-02T09-40-09Z
minio_version_success_string: "{{ minio_version }}"
minio_version_cmd: minio --version
minio_url: "https://dl.min.io/server/minio/release/linux-amd64/archive/minio.{{ minio_version }}"
minio_downloaded_file: "minio.{{ minio_version }}"
minio_extracted_path: "minio.{{ minio_version }}"
minio_symlink_dir: "/usr/local/bin"
