- hosts: all
  tasks:
    - debug:
      msg: " disable_apt_tasks == {{ disable_apt_tasks }}"
    when: disable_apt_tasks

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: "Install apt packages"
      apt:
        state: present
        name:
          - apt-transport-https
          - autofs
          - bmon
          - build-essential
          - ca-certificates
          - curl
          - debconf-utils
          - fio
          - git
          - gnupg-agent
          - htop
          - hwloc
          - inotify-tools
          - iotop
          - jq
          - lm-sensors
          - net-tools
          - nmap
          - parallel
          - pigz
          - postgresql-client-12
          - python3-pip
          - python3-venv
          - rsync
          - screen
          - software-properties-common
          - sqlite3
          - sshpass
          - tree
          - vim
          - webhook
          - wget
          - zip
        update_cache: yes
        cache_valid_time: 1800
      when: not disable_apt_tasks

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - tsdata
    - seaflowpy
    - popcycle
    - ingest
    - chapydette

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - caddy
    - consul
    - consul-template
    - nomad
    - vault
    - grafana
    - timescaledb
    - minio
    - mc
    - rclone
    - hashicorp-realtime-shore
