- hosts: all
  become: yes
  become_method: sudo
  tasks:

  - name: Create jobs_data directory
    become: yes
    file:
      path: "{{ jobs_data }}"
      owner: "{{ realtime_user }}"
      group: "{{ realtime_user }}"
      state: directory

  - name: "Mount VM shared folder"
    ansible.posix.mount:
      path: "{{ jobs_data }}"
      src: jobsdata
      fstype: vboxsf
      opts: "rw,relatime,uid={{ realtime_user }},gid={{ realtime_user }}"
      state: mounted
