- hosts: all
  become: yes
  become_method: sudo
  roles:
    - apt-common
    - docker
    - consul
    - vault
    - nomad
    - golang
    - rclone
    - timescaledb
    - grafana
    - minio
    - mc
