- hosts: all
  tasks:
    - debug:
        msg: " disable_apt_tasks == {{ disable_apt_tasks }}"
      when: disable_apt_tasks

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: "Install apt packages"
      apt:
        state: present
        name:
          - apt-transport-https
          - autofs
          - bmon
          - build-essential
          - ca-certificates
          - cifs-utils
          - curl
          - debconf-utils
          - fio
          - git
          - gnupg-agent
          - htop
          - hwloc
          - inotify-tools
          - iotop
          - jq
          - lm-sensors
          - net-tools
          - nmap
          - parallel
          - pigz
          - postgresql-client-14
          - python3-pip
          - python3-venv
          - rsync
          - samba
          - screen
          - smbclient
          - software-properties-common
          - sqlite3
          - sshpass
          - tree
          - vim
          - webhook
          - wget
          - zip
        update_cache: yes
        cache_valid_time: 1800
      when: not disable_apt_tasks

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - apt-disable-unattended-upgrade

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Check if reboot required
      ansible.builtin.stat:
        path: /var/run/reboot-required
      register: reboot_required_file

    - name: Reboot if required
      reboot:
      when: reboot_required_file.stat.exists == true

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Create jobs_data directory
      become: yes
      file:
        path: "{{ jobs_data }}"
        owner: "{{ realtime_user }}"
        group: "{{ realtime_user }}"
        state: directory

    - name: "Mount VM shared folder"
      ansible.posix.mount:
        path: "{{ jobs_data }}"
        src: jobsdata
        fstype: vboxsf
        opts: "rw,relatime,uid={{ realtime_user }},gid={{ realtime_user }}"
        state: mounted

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - tsdata
    - seaflow-transfer
    - cruisemic
    - seaflog
    - udpcombadge
    - seaflowpy
    - popcycle
    - ingest

- hosts: all
  become: yes
  become_method: sudo
  roles:
    - caddy
    - consul
    - nomad
    - grafana
    - timescaledb
    - minio
    - mc
    - rclone
    - hashicorp-realtime-shore
