- hosts: all
  tasks:
    - debug:
        msg: " disable_apt_tasks == {{ disable_apt_tasks }}"
      when: disable_apt_tasks

- hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: "Install virtualbox guest additions"
      apt:
        state: present
        name:
          - virtualbox-guest-utils
        update_cache: yes
        cache_valid_time: 1800
      when: not disable_apt_tasks
