---
# tasks file for minio

- name: Include executable_downloader role
  include_role:
    name: executable_downloader
  vars:
    execdl_name: "{{ minio_name }}"
    execdl_checksum: "{{ minio_checksum }}"
    execdl_version: "{{ minio_version }}"
    execdl_version_success_string: "{{ minio_version_success_string }}"
    execdl_version_cmd: "{{ minio_version_cmd }}"
    execdl_url: "{{ minio_url }}"
    execdl_downloaded_file: "{{ minio_downloaded_file }}"
    execdl_extracted_path: "{{ minio_extracted_path }}"
    execdl_symlink_dir: "{{ minio_symlink_dir }}"

- name: Create minio group
  ansible.builtin.group:
    name: minio
    gid: 842
    system: yes

- name: Create minio user
  ansible.builtin.user:
    name: minio
    group: minio
    uid: 842
    system: yes

- name: Create minio directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: minio
    group: minio
  loop:
    - "/var/lib/minio"
    - "/var/lib/minio/data"
    - "/var/lib/minio/events"