---
# defaults file for rclone

rclone_name: rclone
rclone_checksum: sha256:6d6455e1cb69eb0615a52cc046a296395e44d50c0f32627ba8590c677ddf50a9
rclone_version: v1.61.1
rclone_version_success_string: "{{ rclone_version }}"
rclone_version_cmd: rclone version
rclone_url: "https://downloads.rclone.org/{{ rclone_version }}/rclone-{{ rclone_version }}-linux-amd64.zip"
rclone_downloaded_file: "rclone-{{ rclone_version }}-linux-amd64.zip"
rclone_extracted_path: "rclone-{{ rclone_version }}-linux-amd64/{{ rclone_name }}"
